### ISSUE TITLE
error when writing gfile from AUGData

### ISSUE THREAD

**Issue by phil-u** [PSFCPlasmaTools/eqtools#9]
I tried to write a gfile from an AUGData equilibrium 

```
e = eqtools.AUGData.AUGDDData(33120, shotfile='EQI', tspline=True)
eqtools.filewriter.gfile(e, 5.5, nw=129, nh=129)
```
an got the following error:

```
Traceback (most recent call last):
  File "/afs/ipp/home/u/ulblp/pyscripts/equi.py", line 34, in <module>
    eqtools.filewriter.gfile(e, time, nw=129, nh=129)
  File "/afs/ipp/home/u/ulblp/.local/lib/python2.7/site-packages/eqtools/filewriter.py", line 221, in gfile
    scipy.atleast_2d(obj.getQProfile()))
  File "/afs/ipp/home/u/ulblp/.local/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py", line 1177, in __init__
    raise ValueError('y dimension of z must have same number of '
ValueError: y dimension of z must have same number of elements as y
```
After some tests I found out that the q-profile has a different size (40) than the other quantities (F, F', etc.) (41) but uses the same x-vector for the interpolation.

The following line fixed it for me (after Line201 in filewriter.py):

`pts0 = scipy.linspace(0.,1.,obj.getQProfile().shape[-1])`

**Comment by icfaust** [comment]
Just be careful about trying to test that on older discharges. There is some inconsistency with shotfiles and how their equilibria are stored in the datasystem. Unfortunately I never got around to writing a unit test for any of that stuff, so please verify those Q profiles to make sure they aren't too odd (especially near the edge).  Also, it could be that such a modification may break the filewriter for other tokamaks, so it could be that we don't add that to it.  While we tried to make it as agnostic to equilibrium solver as possible, things like EFIT put out to gfile and others a bit more naturally.

Please note that the three of us have moved out of fusion science, so we don't have any way anymore of testing the code...

**Comment by icfaust** [comment]
I can't remember if F and F' are directly available in the EQH shotfile. Could you make sure that it is stored properly in the datasystem (aka on the same rho base), I can't rightly remember how I got those values. If some are generated within the python code, rather than being pulled directly from the data, it could also require some special attention.

**Comment by phil-u** [comment]
Thank you for your fast and comprehensive answer!
I checked the q-values for validity and they seemed ok. I think the fix is no problem for the code because these values are then used in the trispline to get it on the same rho basis. But I understand that you do not want to introduce possible problems in the future, especially when you are not into fusion anymore.
I will use the fix in my local copy and will be careful when handling the q-values!
Thanks
